export {
  isAuthentikConfigured,
  hasPendingAuthentikCallback,
  startAuthentikOAuthFlow,
  handleAuthentikCallback,
  readOidcSession,
  clearOidcSession,
  OIDC_INITIAL_SEARCH,
  type OidcClaims,
  type OidcSession,
  type OidcProvider,
  type OidcTokens,
  type AuthentikOidcConfig,
} from '@edcalderon/auth';

export {
  createAuthentikPreset,
  createAuthentikRelayHandler,
  createAuthentikLogoutHandler,
  handleAuthentikCallback as handleAuthentikPresetCallback,
  discoverEndpoints,
  resolveSafeRedirect,
  validateAuthentikConfig,
  validateFullConfig,
  type AuthentikPreset,
  type AuthentikPresetConfig,
  type CreateAuthentikPresetOptions,
  type HandleAuthentikCallbackInput,
  type AuthentikRelayHandler,
  type AuthentikRelayConfig,
  type AuthentikCallbackConfig,
  type AuthentikLogoutConfig,
  type AuthentikEndpoints,
  type AuthentikProvider,
  type AuthentikCallbackResult,
  type ProcessCallbackResult,
  type AuthentikLogoutResult,
  type ProvisioningAdapter,
  type ProvisioningPayload,
  type ProvisioningResult,
  type SafeRedirectConfig,
} from '@edcalderon/auth/authentik';
