/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module 'sst' {
  export interface Resource {
    'expo-assets-production': {
      name: string;
      type: 'sst.aws.Bucket';
    };
    'expo-web-production': {
      type: 'sst.aws.StaticSite';
      url: string;
    };
  }
}
/// <reference path="sst-env.d.ts" />

import 'sst';
export {};
