/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-argument */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable comma-dangle */
/**
 * Template: sst.config.ts
 *
 * Generated by `npx @lsts_tech/infra init`.
 * Provider support in v1.0.0: AWS only.
 */

export default $config({
  app(input: any) {
    return {
      name: process.env.INFRA_APP_NAME ?? 'alternun-infra',
      removal: input?.stage === 'production' ? 'retain' : 'remove',
      protect: ['production'].includes(input?.stage),
      home: 'aws',
      providers: {
        aws: {
          region: (process.env.AWS_REGION ?? 'us-east-1') as aws.Region,
        },
      },
    };
  },
  async run() {
    const { createInfrastructure } = await import('./infra.config.js');
    return createInfrastructure();
  },
});
