export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  AF: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad'],
  AL: ['Tirana', 'Durrës', 'Vlorë', 'Shkodër', 'Fier', 'Korçë'],
  DZ: ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Tlemcen'],
  AD: ['Andorra la Vella', 'Escaldes-Engordany'],
  AO: ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Kuito'],
  AG: ["Saint John's"],
  AR: [
    'Buenos Aires',
    'Córdoba',
    'Rosario',
    'Mendoza',
    'San Miguel de Tucumán',
    'La Plata',
    'Mar del Plata',
    'Salta',
    'Santa Fe',
    'San Juan',
  ],
  AM: ['Yerevan', 'Gyumri', 'Vanadzor'],
  AU: [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Gold Coast',
    'Canberra',
    'Newcastle',
    'Wollongong',
    'Hobart',
  ],
  AT: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt'],
  AZ: ['Baku', 'Ganja', 'Sumqayit', 'Mingəçevir'],
  BS: ['Nassau', 'Freeport'],
  BH: ['Manama', 'Riffa', 'Muharraq'],
  BD: ['Dhaka', 'Chittagong', 'Sylhet', 'Rajshahi', 'Khulna', 'Comilla'],
  BB: ['Bridgetown'],
  BY: ['Minsk', 'Homyel', 'Vitebsk', 'Hrodna', 'Brest', 'Mahilyow'],
  BE: ['Brussels', 'Antwerp', 'Ghent', 'Liège', 'Bruges', 'Namur'],
  BZ: ['Belmopan', 'Belize City'],
  BJ: ['Cotonou', 'Abomey-Calavi', 'Porto-Novo', 'Parakou'],
  BT: ['Thimphu', 'Phuentsholing', 'Punakha'],
  BO: ['Sucre', 'La Paz', 'Santa Cruz de la Sierra', 'Cochabamba', 'Oruro', 'Potosí'],
  BA: ['Sarajevo', 'Banja Luka', 'Mostar', 'Tuzla', 'Zenica'],
  BW: ['Gaborone', 'Francistown', 'Maun', 'Serowe'],
  BR: [
    'São Paulo',
    'Rio de Janeiro',
    'Brasília',
    'Salvador',
    'Fortaleza',
    'Belo Horizonte',
    'Manaus',
    'Curitiba',
    'Recife',
    'Porto Alegre',
    'Belém',
    'Goiânia',
    'Guarulhos',
    'Campinas',
    'Florianópolis',
  ],
  BN: ['Bandar Seri Begawan'],
  BG: ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Ruse'],
  BF: ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou'],
  BI: ['Bujumbura', 'Muyinga', 'Gitega'],
  CV: ['Praia', 'Mindelo'],
  KH: ['Phnom Penh', 'Siem Reap', 'Sihanoukville', 'Battambang'],
  CM: ['Yaoundé', 'Douala', 'Garoua', 'Bamenda', 'Bafoussam'],
  CA: [
    'Toronto',
    'Montreal',
    'Vancouver',
    'Calgary',
    'Edmonton',
    'Ottawa',
    'Winnipeg',
    'Quebec City',
    'Hamilton',
    'Halifax',
    'Victoria',
    'Saskatoon',
    'Regina',
    "St. John's",
  ],
  CF: ['Bangui'],
  TD: ["N'Djamena", 'Moundou', 'Sarh'],
  CL: [
    'Santiago',
    'Valparaíso',
    'Concepción',
    'La Serena',
    'Antofagasta',
    'Temuco',
    'Rancagua',
    'Talca',
    'Arica',
    'Iquique',
    'Puerto Montt',
  ],
  CN: [
    'Beijing',
    'Shanghai',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Chongqing',
    "Xi'an",
    'Wuhan',
    'Hangzhou',
    'Nanjing',
    'Tianjin',
    'Dongguan',
    'Foshan',
    'Shenyang',
    'Qingdao',
  ],
  CO: [
    'Bogotá',
    'Medellín',
    'Cali',
    'Barranquilla',
    'Cartagena',
    'Cúcuta',
    'Soledad',
    'Ibagué',
    'Bucaramanga',
    'Soacha',
    'Pereira',
    'Santa Marta',
    'Manizales',
    'Bello',
    'Pasto',
    'Montería',
    'Villavicencio',
    'Armenia',
    'Valledupar',
    'Neiva',
  ],
  KM: ['Moroni'],
  CD: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani'],
  CG: ['Brazzaville', 'Pointe-Noire'],
  CR: ['San José', 'Alajuela', 'Cartago', 'Heredia', 'Liberia'],
  CI: ['Abidjan', 'Bouaké', 'Daloa', 'Yamoussoukro', 'San-Pédro'],
  HR: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Dubrovnik'],
  CU: ['Havana', 'Santiago de Cuba', 'Camagüey', 'Holguín', 'Santa Clara'],
  CY: ['Nicosia', 'Limassol', 'Larnaca', 'Famagusta'],
  CZ: ['Prague', 'Brno', 'Ostrava', 'Plzeň', 'Liberec', 'Olomouc'],
  DK: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg'],
  DJ: ['Djibouti City'],
  DM: ['Roseau'],
  DO: ['Santo Domingo', 'Santiago de los Caballeros', 'La Romana', 'San Pedro de Macorís'],
  EC: [
    'Quito',
    'Guayaquil',
    'Cuenca',
    'Ambato',
    'Manta',
    'Portoviejo',
    'Machala',
    'Esmeraldas',
    'Loja',
  ],
  EG: [
    'Cairo',
    'Alexandria',
    'Giza',
    'Shubra el-Kheima',
    'Port Said',
    'Suez',
    'Luxor',
    'Aswan',
    'Mansoura',
    'Tanta',
  ],
  SV: ['San Salvador', 'Santa Ana', 'San Miguel', 'Soyapango'],
  GQ: ['Malabo', 'Bata'],
  ER: ['Asmara', 'Keren'],
  EE: ['Tallinn', 'Tartu', 'Narva', 'Pärnu'],
  SZ: ['Mbabane', 'Manzini'],
  ET: ['Addis Ababa', 'Dire Dawa', "Mek'ele", 'Gondar', 'Hawassa', 'Bahir Dar'],
  FJ: ['Suva', 'Lautoka', 'Nadi'],
  FI: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku'],
  FR: [
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Bordeaux',
    'Lille',
    'Rennes',
    'Reims',
    'Le Havre',
    'Toulon',
    'Grenoble',
  ],
  GA: ['Libreville', 'Port-Gentil'],
  GM: ['Banjul', 'Serekunda'],
  GE: ['Tbilisi', 'Kutaisi', 'Batumi', 'Rustavi'],
  DE: [
    'Berlin',
    'Hamburg',
    'Munich',
    'Cologne',
    'Frankfurt',
    'Stuttgart',
    'Düsseldorf',
    'Leipzig',
    'Dortmund',
    'Essen',
    'Bremen',
    'Dresden',
    'Hannover',
    'Nuremberg',
    'Duisburg',
  ],
  GH: ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Cape Coast'],
  GR: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Rhodes'],
  GD: ["Saint George's"],
  GT: ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango', 'Escuintla'],
  GN: ['Conakry', 'Nzérékoré', 'Kankan'],
  GW: ['Bissau'],
  GY: ['Georgetown', 'Linden'],
  HT: ['Port-au-Prince', 'Cap-Haïtien', 'Gonaïves'],
  HN: ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba', 'Choloma'],
  HU: ['Budapest', 'Debrecen', 'Miskolc', 'Győr', 'Pécs', 'Nyíregyháza'],
  IS: ['Reykjavik', 'Akureyri', 'Kópavogur'],
  IN: [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Hyderabad',
    'Ahmedabad',
    'Chennai',
    'Kolkata',
    'Surat',
    'Pune',
    'Jaipur',
    'Lucknow',
    'Kanpur',
    'Nagpur',
    'Indore',
    'Thane',
    'Bhopal',
    'Visakhapatnam',
    'Patna',
    'Vadodara',
    'Ghaziabad',
  ],
  ID: [
    'Jakarta',
    'Surabaya',
    'Bandung',
    'Medan',
    'Bekasi',
    'Tangerang',
    'Depok',
    'Semarang',
    'Palembang',
    'Makassar',
    'Denpasar',
    'Yogyakarta',
    'Bogor',
  ],
  IR: ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Tabriz', 'Shiraz', 'Qom', 'Ahvaz', 'Kermanshah'],
  IQ: ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Kirkuk', 'Najaf'],
  IE: ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford'],
  IL: ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Ashdod'],
  IT: [
    'Rome',
    'Milan',
    'Naples',
    'Turin',
    'Palermo',
    'Genoa',
    'Bologna',
    'Florence',
    'Bari',
    'Catania',
    'Venice',
    'Verona',
    'Messina',
    'Padua',
  ],
  JM: ['Kingston', 'Montego Bay', 'Spanish Town', 'Portmore'],
  JP: [
    'Tokyo',
    'Yokohama',
    'Osaka',
    'Nagoya',
    'Sapporo',
    'Fukuoka',
    'Kobe',
    'Kyoto',
    'Kawasaki',
    'Saitama',
    'Hiroshima',
    'Sendai',
    'Chiba',
    'Kitakyushu',
  ],
  JO: ['Amman', 'Zarqa', 'Irbid', 'Russeifa', 'Wadi as-Sir'],
  KZ: ['Almaty', 'Nur-Sultan', 'Shymkent', 'Karaganda', 'Aktobe'],
  KE: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret'],
  KI: ['Tarawa'],
  KP: ['Pyongyang', 'Hamhung', 'Chongjin'],
  KR: [
    'Seoul',
    'Busan',
    'Incheon',
    'Daegu',
    'Daejeon',
    'Gwangju',
    'Suwon',
    'Ulsan',
    'Seongnam',
    'Goyang',
  ],
  KW: ['Kuwait City', 'Ahmadi', 'Hawalli'],
  KG: ['Bishkek', 'Osh', 'Jalal-Abad'],
  LA: ['Vientiane', 'Luang Prabang', 'Pakse'],
  LV: ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava'],
  LB: ['Beirut', 'Tripoli', 'Sidon', 'Tyre'],
  LS: ['Maseru', 'Teyateyaneng'],
  LR: ['Monrovia', 'Gbarnga', 'Buchanan'],
  LY: ['Tripoli', 'Benghazi', 'Misrata', 'Bayda'],
  LI: ['Vaduz', 'Schaan'],
  LT: ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys'],
  LU: ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange'],
  MG: ['Antananarivo', 'Toamasina', 'Antsirabe', 'Mahajanga'],
  MW: ['Lilongwe', 'Blantyre', 'Mzuzu'],
  MY: [
    'Kuala Lumpur',
    'Subang Jaya',
    'Klang',
    'Johor Bahru',
    'Penang',
    'Kota Kinabalu',
    'Kuching',
    'Ipoh',
    'Shah Alam',
    'Petaling Jaya',
  ],
  MV: ['Malé'],
  ML: ['Bamako', 'Sikasso', 'Mopti', 'Koutiala'],
  MT: ['Valletta', 'Birkirkara', 'Mosta', 'Qormi'],
  MH: ['Majuro', 'Ebeye'],
  MR: ['Nouakchott', 'Nouadhibou'],
  MU: ['Port Louis', 'Beau Bassin-Rose Hill', 'Vacoas-Phoenix'],
  MX: [
    'Mexico City',
    'Guadalajara',
    'Monterrey',
    'Puebla',
    'Tijuana',
    'León',
    'Juárez',
    'Zapopan',
    'Nezahualcóyotl',
    'Mérida',
    'San Luis Potosí',
    'Aguascalientes',
    'Hermosillo',
    'Querétaro',
    'Acapulco',
    'Cancún',
    'Morelia',
    'Veracruz',
    'Culiacán',
  ],
  FM: ['Palikir'],
  MD: ['Chișinău', 'Tiraspol', 'Bălți'],
  MC: ['Monaco'],
  MN: ['Ulaanbaatar', 'Erdenet', 'Darkhan'],
  ME: ['Podgorica', 'Nikšić', 'Budva'],
  MA: [
    'Casablanca',
    'Rabat',
    'Fez',
    'Marrakech',
    'Agadir',
    'Tangier',
    'Meknès',
    'Oujda',
    'Kenitra',
  ],
  MZ: ['Maputo', 'Matola', 'Beira', 'Nampula'],
  MM: ['Naypyidaw', 'Yangon', 'Mandalay', 'Mawlamyine'],
  NA: ['Windhoek', 'Rundu', 'Walvis Bay'],
  NR: ['Yaren'],
  NP: ['Kathmandu', 'Pokhara', 'Lalitpur', 'Bharatpur', 'Birgunj'],
  NL: [
    'Amsterdam',
    'Rotterdam',
    'The Hague',
    'Utrecht',
    'Eindhoven',
    'Groningen',
    'Tilburg',
    'Almere',
    'Breda',
    'Nijmegen',
  ],
  NZ: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Dunedin'],
  NI: ['Managua', 'León', 'Masaya', 'Matagalpa', 'Chinandega'],
  NE: ['Niamey', 'Zinder', 'Maradi', 'Agadez'],
  NG: [
    'Lagos',
    'Kano',
    'Ibadan',
    'Abuja',
    'Port Harcourt',
    'Benin City',
    'Maiduguri',
    'Zaria',
    'Aba',
    'Kaduna',
    'Enugu',
  ],
  MK: ['Skopje', 'Bitola', 'Kumanovo', 'Tetovo'],
  NO: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Drammen', 'Tromsø'],
  OM: ['Muscat', 'Sohar', 'Salalah', 'Nizwa'],
  PK: [
    'Karachi',
    'Lahore',
    'Islamabad',
    'Rawalpindi',
    'Faisalabad',
    'Multan',
    'Peshawar',
    'Quetta',
    'Hyderabad',
    'Gujranwala',
  ],
  PW: ['Ngerulmud', 'Koror'],
  PA: ['Panama City', 'Colón', 'David', 'La Chorrera'],
  PG: ['Port Moresby', 'Lae', 'Mount Hagen'],
  PY: ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiatá'],
  PE: [
    'Lima',
    'Arequipa',
    'Trujillo',
    'Chiclayo',
    'Huancayo',
    'Piura',
    'Iquitos',
    'Cusco',
    'Chimbote',
    'Pucallpa',
  ],
  PH: [
    'Manila',
    'Quezon City',
    'Davao',
    'Caloocan',
    'Zamboanga',
    'Cebu',
    'Antipolo',
    'Pasig',
    'Taguig',
    'Valenzuela',
  ],
  PL: [
    'Warsaw',
    'Kraków',
    'Łódź',
    'Wrocław',
    'Poznań',
    'Gdańsk',
    'Szczecin',
    'Bydgoszcz',
    'Lublin',
    'Katowice',
  ],
  PT: ['Lisbon', 'Porto', 'Amadora', 'Braga', 'Setúbal', 'Coimbra', 'Funchal'],
  QA: ['Doha', 'Al Rayyan', 'Umm Salal Muhammad'],
  RO: ['Bucharest', 'Cluj-Napoca', 'Timișoara', 'Iași', 'Constanța', 'Craiova', 'Brașov'],
  RU: [
    'Moscow',
    'Saint Petersburg',
    'Novosibirsk',
    'Yekaterinburg',
    'Nizhny Novgorod',
    'Samara',
    'Omsk',
    'Kazan',
    'Chelyabinsk',
    'Rostov-on-Don',
    'Ufa',
    'Volgograd',
    'Krasnoyarsk',
    'Saratov',
    'Voronezh',
  ],
  RW: ['Kigali', 'Butare', 'Gisenyi'],
  KN: ['Basseterre'],
  LC: ['Castries'],
  VC: ['Kingstown'],
  WS: ['Apia'],
  SM: ['San Marino'],
  ST: ['São Tomé'],
  SA: ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', "Ta'if", 'Tabuk', 'Buraidah', 'Abha'],
  SN: ['Dakar', 'Touba', 'Thiès', 'Saint-Louis', 'Kaolack'],
  RS: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica'],
  SC: ['Victoria'],
  SL: ['Freetown', 'Bo', 'Kenema'],
  SG: ['Singapore'],
  SK: ['Bratislava', 'Košice', 'Prešov', 'Žilina', 'Nitra'],
  SI: ['Ljubljana', 'Maribor', 'Celje', 'Kranj'],
  SB: ['Honiara'],
  SO: ['Mogadishu', 'Merca', 'Kismayo', 'Hargeisa'],
  ZA: [
    'Johannesburg',
    'Cape Town',
    'Durban',
    'Pretoria',
    'Soweto',
    'Port Elizabeth',
    'Pietermaritzburg',
    'Benoni',
    'Tembisa',
    'East London',
  ],
  SS: ['Juba', 'Wau', 'Malakal'],
  ES: [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Seville',
    'Zaragoza',
    'Málaga',
    'Murcia',
    'Palma',
    'Las Palmas',
    'Bilbao',
    'Alicante',
    'Córdoba',
    'Valladolid',
    'Vigo',
    'Gijón',
  ],
  LK: ['Colombo', 'Kandy', 'Gampaha', 'Moratuwa', 'Jaffna'],
  SD: ['Khartoum', 'Omdurman', 'Port Sudan', 'Kassala'],
  SR: ['Paramaribo', 'Lelydorp'],
  SE: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Linköping', 'Örebro'],
  CH: ['Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern', 'Winterthur', 'Lucerne'],
  SY: ['Damascus', 'Aleppo', 'Homs', 'Hama', 'Latakia'],
  TW: ['Taipei', 'New Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Hsinchu'],
  TJ: ['Dushanbe', 'Khujand', 'Kulob'],
  TZ: ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Mbeya'],
  TH: [
    'Bangkok',
    'Chiang Mai',
    'Nonthaburi',
    'Udon Thani',
    'Nakhon Ratchasima',
    'Pattaya',
    'Phuket',
    'Hat Yai',
    'Khon Kaen',
  ],
  TL: ['Dili'],
  TG: ['Lomé', 'Sokodé', 'Kara'],
  TO: ['Nukuʻalofa'],
  TT: ['Port of Spain', 'Chaguanas', 'San Fernando'],
  TN: ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen', 'Gabès'],
  TR: [
    'Istanbul',
    'Ankara',
    'İzmir',
    'Bursa',
    'Adana',
    'Gaziantep',
    'Konya',
    'Antalya',
    'Kayseri',
    'Mersin',
    'Diyarbakır',
    'Eskişehir',
    'Trabzon',
  ],
  TM: ['Ashgabat', 'Türkmenabat', 'Daşoguz'],
  TV: ['Funafuti'],
  UG: ['Kampala', 'Entebbe', 'Jinja', 'Gulu', 'Mbarara'],
  UA: [
    'Kyiv',
    'Kharkiv',
    'Odessa',
    'Dnipro',
    'Donetsk',
    'Zaporizhzhia',
    'Lviv',
    'Kryvyi Rih',
    'Mykolaiv',
    'Mariupol',
  ],
  AE: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah'],
  GB: [
    'London',
    'Birmingham',
    'Manchester',
    'Glasgow',
    'Liverpool',
    'Bristol',
    'Sheffield',
    'Edinburgh',
    'Leeds',
    'Leicester',
    'Cardiff',
    'Belfast',
    'Coventry',
    'Nottingham',
    'Newcastle',
  ],
  US: [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'San Francisco',
    'Columbus',
    'Fort Worth',
    'Charlotte',
    'Indianapolis',
    'Seattle',
    'Denver',
    'Washington DC',
    'Nashville',
    'Oklahoma City',
    'El Paso',
    'Boston',
    'Las Vegas',
    'Miami',
    'Atlanta',
    'Portland',
    'Minneapolis',
    'New Orleans',
  ],
  UY: ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú', 'Las Piedras'],
  UZ: ['Tashkent', 'Namangan', 'Samarkand', 'Andijan', 'Bukhara'],
  VU: ['Port Vila', 'Luganville'],
  VE: [
    'Caracas',
    'Maracaibo',
    'Maracay',
    'Valencia',
    'Barquisimeto',
    'Maturín',
    'Ciudad Guayana',
    'San Cristóbal',
    'Barcelona',
  ],
  VN: [
    'Ho Chi Minh City',
    'Hanoi',
    'Da Nang',
    'Hai Phong',
    'Can Tho',
    'Bien Hoa',
    'Hue',
    'Nha Trang',
    'Buon Ma Thuot',
  ],
  YE: ["Sana'a", 'Aden', 'Taiz', 'Hodeidah', 'Mukalla'],
  ZM: ['Lusaka', 'Kitwe', 'Ndola', 'Kabwe', 'Livingstone'],
  ZW: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru'],
};

export function getCitiesForCountry(countryCode: string): string[] {
  return CITIES_BY_COUNTRY[countryCode.toUpperCase()] ?? [];
}
