#!/usr/bin/env bash
set -euo pipefail

# ensure-pipelines.sh (template)
#
# AWS-only helper (v1.0.0) to ensure configured CodePipelines exist.
# Missing pipelines are created by triggering an SST deploy for their mapped stage.
#
# Usage:
#   APPROVE=true bash scripts/ensure-pipelines.sh

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
INFRA_DIR=$(cd "$SCRIPT_DIR/.." && pwd)

# shellcheck source=/dev/null
source "$SCRIPT_DIR/_load-infra-env.sh"
load_infra_env

DOMAIN_ROOT=${DOMAIN_ROOT:-${INFRA_ROOT_DOMAIN:-}}
if [ -z "$DOMAIN_ROOT" ]; then
  echo "ERROR: Set DOMAIN_ROOT or INFRA_ROOT_DOMAIN (e.g., example.com)" >&2
  exit 1
fi

REGION=${AWS_REGION:-us-east-1}
REPO_DEFAULT=${INFRA_PIPELINE_REPO:-alternun-development/alternun}
PIPELINE_PREFIX=${INFRA_PIPELINE_PREFIX:-alternun}
IDENTITY_BRANCH_DEV=${INFRA_PIPELINE_BRANCH_IDENTITY_DEV:-${INFRA_PIPELINE_BRANCH_IDENTITY:-develop}}
IDENTITY_BRANCH_PROD=${INFRA_PIPELINE_BRANCH_IDENTITY_PROD:-${INFRA_PIPELINE_BRANCH_PROD:-master}}
API_BRANCH_DEV=${INFRA_PIPELINE_BRANCH_API_DEV:-${INFRA_PIPELINE_BRANCH_API:-${INFRA_PIPELINE_BRANCH_DEV:-develop}}}
API_BRANCH_PROD=${INFRA_PIPELINE_BRANCH_API_PROD:-${INFRA_PIPELINE_BRANCH_API:-${INFRA_PIPELINE_BRANCH_PROD:-master}}}
ADMIN_BRANCH_DEV=${INFRA_PIPELINE_BRANCH_ADMIN_DEV:-${INFRA_PIPELINE_BRANCH_ADMIN:-${INFRA_PIPELINE_BRANCH_DEV:-develop}}}
ADMIN_BRANCH_PROD=${INFRA_PIPELINE_BRANCH_ADMIN_PROD:-${INFRA_PIPELINE_BRANCH_ADMIN:-${INFRA_PIPELINE_BRANCH_PROD:-master}}}
DASHBOARD_BRANCH_DEV=${INFRA_PIPELINE_BRANCH_DASHBOARD_DEV:-${INFRA_PIPELINE_BRANCH_DASHBOARD:-${INFRA_PIPELINE_BRANCH_DEV:-develop}}}
DASHBOARD_BRANCH_PROD=${INFRA_PIPELINE_BRANCH_DASHBOARD_PROD:-${INFRA_PIPELINE_BRANCH_DASHBOARD:-${INFRA_PIPELINE_BRANCH_PROD:-master}}}

# Pipeline definitions (generated by init)
declare -A PIPELINE_STAGE=(
  ["${PIPELINE_PREFIX}-prod"]="production"
  ["${PIPELINE_PREFIX}-dev"]="production"
  ["${PIPELINE_PREFIX}-auth-dev"]="production"
  ["${PIPELINE_PREFIX}-auth-prod"]="production"
  ["${PIPELINE_PREFIX}-api-dev"]="production"
  ["${PIPELINE_PREFIX}-api-prod"]="production"
  ["${PIPELINE_PREFIX}-admin-dev"]="production"
  ["${PIPELINE_PREFIX}-admin-prod"]="production"
  ["${PIPELINE_PREFIX}-dashboard-dev"]="production"
  ["${PIPELINE_PREFIX}-dashboard-prod"]="production"
)
declare -A PIPELINE_REPO=(
  ["${PIPELINE_PREFIX}-prod"]="${REPO_DEFAULT}"
  ["${PIPELINE_PREFIX}-dev"]="${REPO_DEFAULT}"
  ["${PIPELINE_PREFIX}-auth-dev"]="${REPO_DEFAULT}"
  ["${PIPELINE_PREFIX}-auth-prod"]="${REPO_DEFAULT}"
  ["${PIPELINE_PREFIX}-api-dev"]="${REPO_DEFAULT}"
  ["${PIPELINE_PREFIX}-api-prod"]="${REPO_DEFAULT}"
  ["${PIPELINE_PREFIX}-admin-dev"]="${REPO_DEFAULT}"
  ["${PIPELINE_PREFIX}-admin-prod"]="${REPO_DEFAULT}"
  ["${PIPELINE_PREFIX}-dashboard-dev"]="${REPO_DEFAULT}"
  ["${PIPELINE_PREFIX}-dashboard-prod"]="${REPO_DEFAULT}"
)
declare -A PIPELINE_BRANCH=(
  ["${PIPELINE_PREFIX}-prod"]="${INFRA_PIPELINE_BRANCH_PROD:-master}"
  ["${PIPELINE_PREFIX}-dev"]="${INFRA_PIPELINE_BRANCH_DEV:-develop}"
  ["${PIPELINE_PREFIX}-auth-dev"]="$IDENTITY_BRANCH_DEV"
  ["${PIPELINE_PREFIX}-auth-prod"]="$IDENTITY_BRANCH_PROD"
  ["${PIPELINE_PREFIX}-api-dev"]="$API_BRANCH_DEV"
  ["${PIPELINE_PREFIX}-api-prod"]="$API_BRANCH_PROD"
  ["${PIPELINE_PREFIX}-admin-dev"]="$ADMIN_BRANCH_DEV"
  ["${PIPELINE_PREFIX}-admin-prod"]="$ADMIN_BRANCH_PROD"
  ["${PIPELINE_PREFIX}-dashboard-dev"]="$DASHBOARD_BRANCH_DEV"
  ["${PIPELINE_PREFIX}-dashboard-prod"]="$DASHBOARD_BRANCH_PROD"
)

resolve_sst_deploy_script() {
  local candidates=(
    "$SCRIPT_DIR/sst-deploy.sh"
    "$INFRA_DIR/node_modules/@lsts_tech/infra/scripts/sst-deploy.sh"
    "$INFRA_DIR/../node_modules/@lsts_tech/infra/scripts/sst-deploy.sh"
  )

  for candidate in "${candidates[@]}"; do
    if [ -f "$candidate" ]; then
      echo "$candidate"
      return 0
    fi
  done

  return 1
}

if ! command -v aws >/dev/null 2>&1; then
  echo "aws CLI not found in PATH" >&2
  exit 1
fi

if [ ${#PIPELINE_STAGE[@]} -eq 0 ]; then
  echo "No pipelines configured in scripts/ensure-pipelines.sh. Nothing to do."
  exit 0
fi

SST_DEPLOY_SCRIPT=${SST_DEPLOY_SCRIPT:-}
if [ -z "$SST_DEPLOY_SCRIPT" ]; then
  SST_DEPLOY_SCRIPT=$(resolve_sst_deploy_script || true)
fi

if [ -z "$SST_DEPLOY_SCRIPT" ]; then
  echo "Could not locate sst-deploy.sh. Set SST_DEPLOY_SCRIPT explicitly." >&2
  exit 1
fi

cd "$INFRA_DIR"

MISSING=()
for NAME in "${!PIPELINE_STAGE[@]}"; do
  PIPELINE_NAME="${NAME}-pipeline"
  echo "Checking for pipeline names: $NAME or $PIPELINE_NAME (region: $REGION)"

  if aws codepipeline get-pipeline --name "$NAME" --region "$REGION" >/dev/null 2>&1 || \
     aws codepipeline get-pipeline --name "$PIPELINE_NAME" --region "$REGION" >/dev/null 2>&1; then
    echo "Pipeline exists: $PIPELINE_NAME"
  else
    echo "Pipeline missing: $PIPELINE_NAME"
    MISSING+=("$NAME")
  fi
done

if [ ${#MISSING[@]} -eq 0 ]; then
  echo "All pipelines present; nothing to do."
  exit 0
fi

echo "Missing pipelines: ${MISSING[*]}"

if [ "${APPROVE:-}" != "true" ]; then
  echo "To create missing pipelines, re-run with APPROVE=true."
  exit 1
fi

for NAME in "${MISSING[@]}"; do
  STAGE=${PIPELINE_STAGE[$NAME]:-production}
  REPO=${PIPELINE_REPO[$NAME]:-$REPO_DEFAULT}
  BRANCH=${PIPELINE_BRANCH[$NAME]:-main}

  echo "Creating pipeline '$NAME' via SST deploy (stage: $STAGE, repo: $REPO, branch: $BRANCH)"
  APPROVE=true STACK="$STAGE" bash "$SST_DEPLOY_SCRIPT"
done

echo "Done. Current pipelines:"
aws codepipeline list-pipelines --region "$REGION" --query "pipelines[].name" --output table || true
