#!/usr/bin/env bash
set -euo pipefail

# ensure-pipelines.sh (template)
#
# AWS-only helper to ensure configured CodePipelines exist.
# Missing pipelines are repaired by reconciling the production pipeline stack with the
# canonical managed pipeline set.
#
# Usage:
#   APPROVE=true bash scripts/ensure-pipelines.sh

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
INFRA_DIR=$(cd "$SCRIPT_DIR/.." && pwd)

# shellcheck source=/dev/null
source "$SCRIPT_DIR/_load-infra-env.sh"
load_infra_env
# shellcheck source=/dev/null
source "$SCRIPT_DIR/_pipeline-safety.sh"

DOMAIN_ROOT=${DOMAIN_ROOT:-${INFRA_ROOT_DOMAIN:-}}
if [ -z "$DOMAIN_ROOT" ]; then
  echo "ERROR: Set DOMAIN_ROOT or INFRA_ROOT_DOMAIN (e.g., example.com)" >&2
  exit 1
fi

REGION=${AWS_REGION:-us-east-1}
REPO_DEFAULT=${INFRA_PIPELINE_REPO:-alternun-development/alternun}
PIPELINE_PREFIX=${INFRA_PIPELINE_PREFIX:-alternun}
IDENTITY_BRANCH_DEV=${INFRA_PIPELINE_BRANCH_IDENTITY_DEV:-${INFRA_PIPELINE_BRANCH_IDENTITY:-develop}}
IDENTITY_BRANCH_PROD=${INFRA_PIPELINE_BRANCH_IDENTITY_PROD:-${INFRA_PIPELINE_BRANCH_PROD:-master}}
DASHBOARD_BRANCH_DEV=${INFRA_PIPELINE_BRANCH_DASHBOARD_DEV:-${INFRA_PIPELINE_BRANCH_DASHBOARD:-${INFRA_PIPELINE_BRANCH_DEV:-develop}}}
DASHBOARD_BRANCH_PROD=${INFRA_PIPELINE_BRANCH_DASHBOARD_PROD:-${INFRA_PIPELINE_BRANCH_DASHBOARD:-${INFRA_PIPELINE_BRANCH_PROD:-master}}}
TARGET_PIPELINES=${INFRA_MANAGED_PIPELINES_CANONICAL:-$(resolve_canonical_managed_pipeline_csv)}

# Pipeline definitions (generated by init)
declare -A PIPELINE_STAGE=(
  ["production"]="production"
  ["dev"]="production"
  ["identity-dev"]="production"
  ["identity-prod"]="production"
  ["dashboard-dev"]="production"
  ["dashboard-prod"]="production"
)
declare -A PIPELINE_BRANCH=(
  ["production"]="${INFRA_PIPELINE_BRANCH_PROD:-master}"
  ["dev"]="${INFRA_PIPELINE_BRANCH_DEV:-develop}"
  ["identity-dev"]="$IDENTITY_BRANCH_DEV"
  ["identity-prod"]="$IDENTITY_BRANCH_PROD"
  ["dashboard-dev"]="$DASHBOARD_BRANCH_DEV"
  ["dashboard-prod"]="$DASHBOARD_BRANCH_PROD"
)

resolve_sst_deploy_script() {
  local candidates=(
    "$SCRIPT_DIR/sst-deploy.sh"
    "$INFRA_DIR/node_modules/@lsts_tech/infra/scripts/sst-deploy.sh"
    "$INFRA_DIR/../node_modules/@lsts_tech/infra/scripts/sst-deploy.sh"
  )

  for candidate in "${candidates[@]}"; do
    if [ -f "$candidate" ]; then
      echo "$candidate"
      return 0
    fi
  done

  return 1
}

if ! command -v aws >/dev/null 2>&1; then
  echo "aws CLI not found in PATH" >&2
  exit 1
fi

if [ ${#PIPELINE_STAGE[@]} -eq 0 ]; then
  echo "No pipelines configured in scripts/ensure-pipelines.sh. Nothing to do."
  exit 0
fi

SST_DEPLOY_SCRIPT=${SST_DEPLOY_SCRIPT:-}
if [ -z "$SST_DEPLOY_SCRIPT" ]; then
  SST_DEPLOY_SCRIPT=$(resolve_sst_deploy_script || true)
fi

if [ -z "$SST_DEPLOY_SCRIPT" ]; then
  echo "Could not locate sst-deploy.sh. Set SST_DEPLOY_SCRIPT explicitly." >&2
  exit 1
fi

cd "$INFRA_DIR"

declare -A TARGET_KEYS=()
while IFS= read -r PIPELINE_KEY; do
  [ -n "$PIPELINE_KEY" ] && TARGET_KEYS["$PIPELINE_KEY"]=1
done < <(emit_pipeline_keys_from_csv "$TARGET_PIPELINES")

if [ "${#TARGET_KEYS[@]}" -eq 0 ]; then
  echo "No managed pipelines resolved from TARGET_PIPELINES='${TARGET_PIPELINES}'. Nothing to do."
  exit 0
fi

MISSING=()
for PIPELINE_KEY in "${!TARGET_KEYS[@]}"; do
  NAME=$(pipeline_name_for_key "$PIPELINE_KEY" "$PIPELINE_PREFIX")
  echo "Checking for pipeline name: $NAME (region: $REGION)"

  if aws codepipeline get-pipeline --name "$NAME" --region "$REGION" >/dev/null 2>&1; then
    echo "Pipeline exists: $NAME"
  else
    echo "Pipeline missing: $NAME"
    MISSING+=("$PIPELINE_KEY")
  fi
done

if [ ${#MISSING[@]} -eq 0 ]; then
  echo "All pipelines present; nothing to do."
  exit 0
fi

echo "Missing pipelines: ${MISSING[*]}"

if [ "${APPROVE:-}" != "true" ]; then
  echo "To create missing pipelines, re-run with APPROVE=true."
  exit 1
fi

echo "Reconciling the production pipeline stack with canonical pipeline set: ${TARGET_PIPELINES}"
for PIPELINE_KEY in "${!TARGET_KEYS[@]}"; do
  echo "- ${PIPELINE_KEY} -> $(pipeline_name_for_key "$PIPELINE_KEY" "$PIPELINE_PREFIX") (branch: ${PIPELINE_BRANCH[$PIPELINE_KEY]:-main})"
done

export INFRA_PIPELINES="$TARGET_PIPELINES"
export INFRA_ENFORCE_PIPELINE_DELETE_GUARD=true

APPROVE=true STACK="production" bash "$SST_DEPLOY_SCRIPT"

echo "Done. Current pipelines:"
aws codepipeline list-pipelines --region "$REGION" --query "pipelines[].name" --output table || true
