import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const packageJsonPath = path.join(repoRoot, 'package.json');
const releaseScriptPath = path.join(repoRoot, 'scripts', 'release.mjs');
const preCommitPath = path.join(repoRoot, '.husky', 'pre-commit');

void test('release patch stays wired to the release script and auto deploys testnet', () => {
  const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
  const releaseSource = fs.readFileSync(releaseScriptPath, 'utf8');
  const preCommitSource = fs.readFileSync(preCommitPath, 'utf8');

  assert.equal(packageJson.scripts['release:patch'], 'node scripts/release.mjs patch');
  assert.match(releaseSource, /deploy-testnet-api\.sh/);
  assert.match(releaseSource, /--no-prompt/);
  assert.match(releaseSource, /pnpm release:patch/);
  assert.match(releaseSource, /function resolveGitHubRepoSlug/);
  assert.match(releaseSource, /gh api repos\/\$\{repoSlug\}\/pulls/);
  assert.match(releaseSource, /<!-- alternun-release:patch -->/);
  assert.match(releaseSource, /## Release scope/);
  assert.match(releaseSource, /## Release summary/);
  assert.match(releaseSource, /## Affected surfaces/);
  assert.match(releaseSource, /function getLatestProductionTag\(version\)/);
  assert.match(releaseSource, /tag !== `v\$\{version\}`/);
  assert.match(releaseSource, /git', \['diff', '--name-only', `\$\{previousTag\}\.\.HEAD`\]/);
  assert.match(releaseSource, /prefix: 'apps\/api\//);
  assert.match(releaseSource, /name: 'Backend API'/);
  assert.match(releaseSource, /prefix: 'apps\/mobile\//);
  assert.match(releaseSource, /name: 'AIRS client'/);
  assert.match(releaseSource, /prefix: 'packages\/infra\//);
  assert.match(releaseSource, /name: 'Cloud infrastructure'/);
  assert.match(releaseSource, /prefix: '\.github\//);
  assert.match(releaseSource, /name: 'GitHub automation'/);
  assert.match(releaseSource, /## Commit details/);
  assert.match(releaseSource, /apps\/mobile\/version\.development\.json/);
  assert.match(releaseSource, /apps\/mobile\/version\.production\.json/);
  assert.match(releaseSource, /'README\.md'/);
  assert.match(
    releaseSource,
    /if \(!options\.dryRun\) \{\s*syncRootReadme\(\{\s*branch: releaseBranch,\s*version,\s*\}\)/
  );
  assert.match(releaseSource, /gh api PATCH failed/);
  assert.match(releaseSource, /Release promotion cannot open or update the PR automatically/);
  assert.match(releaseSource, /gh api failed to open or update the PR automatically/);
  assert.doesNotMatch(releaseSource, /Create the PR manually/);
  assert.doesNotMatch(releaseSource, /Create the release PR manually/);
  assert.match(releaseSource, /--allow-empty/);
  assert.match(
    releaseSource,
    /createReleaseCommit\(version, options\.dryRun, releaseBranch, options\.promote\)/
  );
  assert.doesNotMatch(releaseSource, /gh pr edit/);
  assert.doesNotMatch(releaseSource, /gh pr create/);
  assert.match(releaseSource, /ALTERNUN_RELEASE_COMMIT/);
  assert.match(releaseSource, /tag', '--list', `v\$\{version\}`/);
  assert.match(releaseSource, /already exists; skipping tag creation/);
  assert.match(preCommitSource, /ALTERNUN_RELEASE_COMMIT/);
  assert.match(preCommitSource, /Skipping lint-staged for autogenerated release commit/);
});
